### ISSUE TITLE
Uncaught TypeError: setPaymentMethodAction(...).success is not a function

### ISSUE THREAD

**Issue by lytesaber** [zipMoney/zip.magento2#66]
- Magento 2.4.4
- PHP 7.4 & PHP 8.1
- Zip 1.1.11

Unable to checkout with Zip payment method since Magento 2.4.4 upgrade. On checkout selecting zip and clicking continue to redirect to zip checkout causes the following error in console and doesn't proceed any further.

> Uncaught TypeError: setPaymentMethodAction(...).success is not a function zip-zippayment.js:59
>     at UiClass.continueToZipMoney (zip-zippayment.js:59:26)
>     at HTMLButtonElement.<anonymous> (knockout.js:4669:74)
>     at HTMLButtonElement.dispatch (jquery.js:5430:49)
>     at HTMLButtonElement.elemData.handle (jquery.js:5234:47)

**Comment by lytesaber** [comment]
Found this was due to a outdated version of the Jquery Migrate Lib JS file that was overwritten in frontend theme. Updating override to latest version from Magento 2.4.4 core lib resolved issue. Zip payment method now processing as expected.
